### GENERATE NEW ACCESS TOKEN
POST http://localhost:3000/api/v1/auth/refreshtoken

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM0NjE0NTVkLTc2MGUtNDE3YS05YjI4LWFiNDIwZWU5YThmZiIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IkRvZSIsImVtYWlsIjoiaGVsbG9Aam9obmRvZS5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTY5MjA4NDI3NiwiZXhwIjoxNjk0Njc2Mjc2fQ.woTZ0TE3Ou9-5XRUxhFXNvYyD85ElRqAlUwKtcDeD9M"
}